In [1]:
from os.path import join
import pandas as pd
from constants import *

# 2011
------------

<br>

### DATASETS

BLOGS: 120,000 articles

BOOKS: 1,000 books

NEWS: 29,000 articles

PUBMED: 77,000 articles

<br>

### TOPIC MODELING pipeline:

- token -> lemma -> stop -> filter out token w/ count < 10 in vocabulary 
- BOW for each document
- 100 topic models
- average PMI score for each topic (Newman 2010b) -> filter out topics w/ score < 0.4
- filter out topics w/ count(token: token default nominal in Wikipedia) < 5

<br>

### RESULTS

| **topics**        | **dataset**       |
| ------------- |:-------------:|
| 45            | BLOGS         |
| 38            | BOOKS         |
| 60            | NEWS          |
| 85            | PUBMED        |
| *228*            | *sum*         |


=> 6000 labels (~27 per topic)

<br> 

#### annotation task:

per topic:
- 10 top topic terms
- 10 label suggestions
- 4 answer options

10 annotations (at least) per label candidate

-> filtered malitious annotators

<br>

45,533 label ratings => ~4,500 successfull HITs (Amazon Mechanical Turk)

In [2]:
data_2011 = '../data/topiclabel/2011'
f_topics2011 = join(data_2011, 'topics.csv')
f_annotation2011 = join(data_2011, 'topiclabels.csv')
readme = join(data_2011, 'README.txt')
topics2011 = pd.read_csv(f_topics2011)
annotation2011 = pd.read_csv(f_annotation2011)

print(annotation2011.iloc[:, 2:].count().sum())
examples = ['2008 summer olympics', 'gothic architecture', 'israeliâ€“palestinian conflict', 'immune system']
mask11 = annotation2011.label.isin(examples)
annotation2011['mean'] = annotation2011.loc[mask11, 'rate0':].mean(axis=1)
annotation2011.loc[mask11]

45533

,topic_id,label,rate0,rate1,rate2,rate3,rate4,rate5,rate6,rate7,rate8,rate9,rate10,rate11,rate12,rate13,mean
244,6,immune system,0,1,1,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.142857
323,9,2008 summer olympics,2,2,3,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.600000
1551,45,gothic architecture,2,2,2,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.400000
1948,61,gothic architecture,1,1,2,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.600000
2334,75,gothic architecture,1,1,2,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.666667
2592,84,israeliâ€“palestinian conflict,2,2,2,3.0,3.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.625000
2662,86,immune system,1,1,1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.166667
4615,145,immune system,0,1,2,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.666667
4645,146,immune system,1,2,2,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,NaN,NaN,NaN,2.363636
6000,195,immune system,1,1,1,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.400000
6899,225,immune system,1,1,1,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.285714

In [3]:
annotation2011[annotation2011.duplicated('label', keep=False)].sort_values('label')

,topic_id,label,rate0,rate1,rate2,rate3,rate4,rate5,rate6,rate7,rate8,rate9,rate10,rate11,rate12,rate13,mean
258,7,1/2 cup,1,1,1,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
381,11,1/2 cup,0,0,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2740,89,1/2 cup,0,0,0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3321,105,1/2 cup,0,0,0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN
259,7,1/4 cup,1,1,1,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382,11,1/4 cup,0,0,0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2741,89,1/4 cup,0,0,0,0.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3323,105,1/4 cup,0,0,1,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3898,122,1960s in fashion,0,1,1,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,NaN,NaN
1138,34,1960s in fashion,1,1,1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3133,100,1988,0,0,0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,5,1988,0,0,0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
962,29,2003 invasion,1,1,1,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2259,73,2003 invasion,0,1,1,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
963,29,2003 invasion of iraq,1,2,2,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260,73,2003 invasion of iraq,0,1,1,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2543,83,2008,0,0,0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,1,2008,1,1,1,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2608,85,2009 in baseball,1,1,1,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3431,109,2009 in baseball,1,2,2,2.0,2.0,2.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
1102,33,25 article,0,0,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1072,32,25 article,0,0,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1850,57,742 evergreen terrace,0,1,1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3988,125,742 evergreen terrace,0,0,0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1531,45,abbey,1,1,1,1.0,2.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316,75,abbey,1,1,2,2.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,30,abbey,0,0,0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
5254,168,acid,0,1,1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6262,204,acid,0,0,0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6769,222,acid,0,1,1,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1648,48,word,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
2542,82,word,1,1,1,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6585,215,working memory,0,0,0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6666,218,working memory,1,2,2,2.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,29,world war,1,1,2,2.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2292,73,world war,1,2,2,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2488,80,world war,0,0,1,1.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2293,73,world war i,1,2,2,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1005,29,world war i,1,2,2,2.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2489,80,world war i,0,1,1,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
539,15,world wide web,2,2,3,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3641,114,world wide web,0,0,0,0.0,0.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5304,169,wound healing,0,0,1,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,3.0,NaN,NaN,NaN
4967,157,wound healing,0,1,1,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1355,39,write,0,1,1,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1264,36,write,1,1,2,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3642,114,write,1,1,1,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN
4225,132,wyandanch,0,0,0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2212,70,wyandanch,0,0,0,0.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2213,70,"wyandanch, new york",0,0,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4226,132,"wyandanch, new york",0,0,0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5747,186,x-ray diffraction,0,0,1,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6488,211,x-ray diffraction,0,0,0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
2258,72,young,0,1,1,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3941,123,young,0,1,1,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6088,197,young,0,1,2,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3942,123,young child,0,1,2,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1219,35,young child,1,1,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
736,21,young girl,0,0,0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1220,35,young girl,0,1,1,1.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(topics2011.shape[0])
topics2011.iloc[[7, 11, 89, 105]]

228

,topic_id,domain,term0,term1,term2,term3,term4,term5,term6,term7,term8,term9
7,7,blogs,food,eat,cook,chicken,recipe,cup,cheese,add,taste,tomato
11,11,blogs,look,white,color,black,red,hair,blue,light,green,eye
89,89,news,food,wine,restaurant,eat,drink,bottle,beer,coffee,bar,ice
105,105,news,cup,cook,minute,add,pepper,salt,serve,tablespoon,oil,sauce

# 2016
------

<br>

### DATASETS and annotation

- same datasets and topics as 2011
- very similar annotation method
- annotation quality controlled by 2011 dataset mean ratings

<br>

- 19 top candidates from unsupervised relevance ranking
- 10 annotations per label candidate (pre-filtering)
- 6.4 annotations per label candidate on average (post-filtering)


<br> 

#### annotation task:

per topic:
- 10 top topic terms
- 10 label suggestions
- 4 answer options

<br>

27,788 label ratings => ~2,800 successfull HITs (CrowdFlower)

<br>

compute mean of ratings and rank accordingly

In [6]:
data_2016 = '../data/topiclabel/2016'
f_topics2016 = join(data_2016, 'topics.csv')
f_annotation2016 = join(data_2016, 'annotated_dataset.csv')
topics2016 = pd.read_csv(f_topics2016)
annotation2016 = pd.read_csv(f_annotation2016, sep='\t')

print(annotation2016.iloc[:, 2:].count().sum())
mask11 = annotation2016.label.isin(examples)
annotation2016['mean'] = annotation2016.loc[mask11, 'annotator1':].mean(axis=1)
annotation2016.loc[mask11]

27788

,label,topic_id,annotator1,annotator2,annotator3,annotator4,annotator5,annotator6,annotator7,annotator8,annotator9,annotator10,mean
175,2008 summer olympics,9.0,3,3,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.500000
855,gothic architecture,45.0,3,1,2.0,1.0,3.0,1.0,2.0,NaN,NaN,NaN,1.857143
1177,gothic architecture,61.0,1,0,2.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,1.666667
1430,gothic architecture,75.0,3,2,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.666667
2027,immune system,106.0,0,0,0.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,0.600000
2783,immune system,146.0,2,3,3.0,2.0,1.0,3.0,2.0,NaN,NaN,NaN,2.285714
2833,immune system,149.0,1,1,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,1.333333
2899,immune system,152.0,2,3,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.800000
2960,immune system,155.0,1,2,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.400000
2989,immune system,157.0,2,2,2.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,1.833333
3224,immune system,169.0,2,0,0.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.200000
3718,immune system,195.0,1,3,2.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,2.200000

In [7]:
annotation2016[annotation2016.duplicated('label', keep=False)].sort_values('label')

,label,topic_id,annotator1,annotator2,annotator3,annotator4,annotator5,annotator6,annotator7,annotator8,annotator9,annotator10,mean
683,a woman,35.0,1,2,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN
1383,a woman,72.0,2,2,2.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN
2680,a woman,141.0,3,1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
656,a woman,34.0,3,2,1.0,2.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN
3404,abdominal surgery,179.0,2,2,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN
1018,abdominal surgery,53.0,2,1,1.0,0.0,3.0,3.0,2.0,2.0,NaN,NaN,NaN
3692,acetylcholine,194.0,2,1,2.0,2.0,1.0,0.0,2.0,2.0,NaN,NaN,NaN
2883,acetylcholine,151.0,2,1,3.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3512,acetylcholine,184.0,2,3,2.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN
3853,acetylcysteine,202.0,2,0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
4136,acetylcysteine,217.0,1,0,1.0,1.0,2.0,3.0,1.0,NaN,NaN,NaN,NaN
3933,acetylcysteine,207.0,1,1,0.0,1.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN
428,acquittal,22.0,1,2,3.0,3.0,3.0,2.0,2.0,2.0,2.0,NaN,NaN
2266,acquittal,119.0,1,2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,actin,17.0,1,1,1.0,2.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN
3612,actin,190.0,1,1,0.0,3.0,1.0,1.0,2.0,1.0,NaN,NaN,NaN
3686,actin,194.0,1,3,1.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
2795,actin,147.0,1,1,2.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN
3350,actin,176.0,0,3,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3688,action potential,194.0,1,1,1.0,0.0,2.0,2.0,2.0,2.0,3.0,NaN,NaN
3508,action potential,184.0,2,0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN
4231,activated carbon,222.0,0,1,1.0,1.0,1.0,1.0,1.0,2.0,1.0,NaN,NaN
3548,activated carbon,186.0,2,3,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4322,activated carbon,227.0,2,0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4289,activation,225.0,1,1,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
3784,activation,199.0,1,1,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,NaN
3826,addiction,201.0,1,2,1.0,2.0,3.0,1.0,2.0,NaN,NaN,NaN,NaN
3740,addiction,196.0,3,2,0.0,2.0,2.0,2.0,3.0,2.0,1.0,2.0,NaN
2752,adenocarcinoma,144.0,3,2,1.0,2.0,1.0,0.0,1.0,1.0,NaN,NaN,NaN
3082,adenocarcinoma,162.0,3,3,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,windows mobile,2.0,1,2,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,windows mobile,18.0,1,2,0.0,2.0,2.0,3.0,2.0,1.0,3.0,1.0,NaN
723,windows mobile,38.0,1,0,1.0,0.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN
739,windows phone,38.0,0,0,2.0,0.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN
348,windows phone,18.0,0,0,3.0,1.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN
734,windows phone 7,38.0,1,0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
350,windows phone 7,18.0,0,3,3.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN
47,windows server 2003,2.0,2,3,1.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN
14,windows server 2003,0.0,1,1,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN
43,windows server 2008,2.0,2,2,1.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
13,windows server 2008,0.0,0,2,1.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
2037,winning streak (sports),107.0,0,0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2457,winning streak (sports),129.0,2,2,1.0,2.0,2.0,2.0,1.0,0.0,2.0,NaN,NaN
2064,winning streak (sports),108.0,1,1,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN
490,winning streak (sports),25.0,3,2,1.0,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN
1925,winning streak (sports),101.0,1,1,1.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN
4145,working memory,218.0,1,2,2.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN
4089,working memory,215.0,1,2,2.0,3.0,0.0,1.0,2.0,1.0,1.0,NaN,NaN
382,world series,20.0,0,3,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2035,world series,107.0,0,1,0.0,2.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN
3216,wound healing,169.0,0,2,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4133,wound healing,217.0,2,2,3.0,2.0,3.0,1.0,2.0,1.0,1.0,NaN,NaN
1582,write-in candidate,83.0,1,2,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,write-in candidate,5.0,2,2,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN
1915,write-in candidate,100.0,3,3,1.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1495,writer,78.0,3,2,3.0,1.0,3.0,2.0,3.0,2.0,2.0,NaN,NaN
694,writer,36.0,1,1,3.0,2.0,3.0,1.0,3.0,2.0,NaN,NaN,NaN
2174,writer,114.0,3,1,2.0,2.0,2.0,3.0,2.0,2.0,NaN,NaN,NaN
1289,you,67.0,1,0,0.0,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN
717,you,37.0,1,0,0.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN

In [8]:
print(topics2016.shape[0])
topics2016.iloc[[35, 72, 141, 34]]

228

,topic_id,domain,term0,term1,term2,term3,term4,term5,term6,term7,term8,term9
35,35,blogs,child,woman,family,kid,parent,baby,mother,home,husband,young
72,72,iabooks,mr.,mrs.,young,lady,look,friend,tell,mother,miss,father
141,141,news,woman,ms.,sex,sexual,male,female,age,bill,begin,husband
34,34,blogs,wear,baby,dress,wedding,look,love,clothes,girl,kid,need